export const route = {
  welcome: "/",
  login: "/login",
  register: "/register",
  verifyEmail: "/verify-email",
  blog: "/blog",
  blogDetail: "/blog/:id",
  home: "/home",
  otpPage: "/otp",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  emailVerified: "/email-verified",
  introWorkspace: "intro-workspace",
  workspace: "/workspace",
  project: "project",
  board: "board",
  userProfile: "user-profile",
  setting: "setting",
  projectSetting: "project-setting",
  projectHistory: "project-history",
  summary: "summary",

  admin: "/admin",
  feedbackManage: "feedback-manage",
  dashboard: "dashboard",
  projectStatistic: "project-statistic",
  adminUser: "manage-user",
  newsManagement: "news-management",
  projectIssue: "project-issue",
};
