export const route = {
  welcome: "/",
  login: "/login",
  register: "/register",
  verifyEmail: "/verify-email",
  blog: "/blog",
  blogDetail: "/blog/:id",
  home: "/home",
  otpPage: "/otp",
  emailVerified: "/email-verified",
  introWorkspace: "intro-workspace",

  workspace: "/workspace",
  project: "project",
  board: "board",
  userProfile: "user-profile",
  setting: "setting",
  projectSetting: "project-setting",

  admin: "/admin",
  dashboard: "dashboard",
  projectStatistic: "project-statistic",
  adminUser: "manage-user",
  newsManagement: "news-management",
  projectIssue: "project-issue",
};
